# Generated by Django 3.1 on 2020-08-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('P', 'Profit'), ('L', 'Loss')], max_length=10)),
                ('net_profit', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance', models.FloatField()),
                ('date', models.DateField()),
                ('recorder', models.BigIntegerField()),
            ],
        ),
    ]
