# Generated by Django 3.1 on 2020-08-30 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_date',
            field=models.DateTimeField(default=datetime.date(2020, 8, 31)),
        ),
    ]
