# Generated by Django 3.1 on 2020-08-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='discount_policy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('phone', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('gender', models.BooleanField(default=0)),
                ('nation', models.CharField(max_length=20)),
                ('join_date', models.DateField(default='2020-01-01')),
                ('credit', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('member_class', models.IntegerField(default=1)),
                ('email', models.CharField(max_length=30)),
                ('birthday', models.DateField(default='2001-01-01')),
                ('discount', models.FloatField(default=1.0)),
            ],
        ),
    ]
