# Generated by Django 3.1 on 2020-08-30 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount_policy',
            old_name='content',
            new_name='policy_content',
        ),
        migrations.RenameField(
            model_name='discount_policy',
            old_name='id',
            new_name='policy_id',
        ),
        migrations.AddField(
            model_name='discount_policy',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
        migrations.AddField(
            model_name='discount_policy',
            name='person_in_charge',
            field=models.BigIntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='discount_policy',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
    ]
