# Generated by Django 3.1 on 2020-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_auto_20200831_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_policy',
            name='end_date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='discount_policy',
            name='start_date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
