# Generated by Django 3.1 on 2020-08-31 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0003_auto_20200831_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_policy',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
        migrations.AlterField(
            model_name='discount_policy',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
    ]
