# Generated by Django 3.1 on 2020-08-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telephone',
        ),
        migrations.AddField(
            model_name='deposit',
            name='phone_number',
            field=models.BigIntegerField(default=15204031275),
            preserve_default=False,
        ),
    ]
