# Generated by Django 3.1 on 2020-08-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200830_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposit_mem',
            new_name='Deposit',
        ),
    ]
