# Generated by Django 3.1 on 2020-08-30 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200830_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
